<?php if ($this->param("process") == "success"): ?>

	<?php $data = $this->param("data"); ?>

    <?php if (count($data)): ?>
    	<div class="sql-data" style="height: 180px; overflow: auto;">
			<table class="ui very compact celled collapsing table">
				<thead>
					<?php $column_names = $data[0]; ?>
					<tr>
						<?php foreach($column_names as $key => $row): ?>
							<?php if (!is_numeric($key)): ?>
								<th><?= $key ?></th>
							<?php endif; ?>
						<?php endforeach; ?>
					</tr>
				</thead>
				<tbody>
					<?php foreach($data as $row): ?>
						<tr>
							<?php for ($i = 0; $i < count($data[0]) / 2; $i++): ?>
								<?php if (is_object($row[$i]) && get_class($row[$i]) == 'DateTime'): $row[$i] = $row[$i]->format("Y-m-d H:i:s"); endif; ?>
								<td><?= !is_null($row[$i]) ? '<pre style="margin: 0">'.$row[$i].'</pre>' : '<span class="ui orange label">NULL</span>' ?></td>
							<?php endfor; ?>
						</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
    	</div>

    <?php else: ?>
    	<div class="alert alert-warning">
    		Nothing to print!.
    	</div>
   	<?php endif ?>

		<br />
    	<strong><?= $this->param('num_rows') ?></strong> rows!.<br />
    	<strong><?= $this->param('num_fields') ?></strong> fields.<br />
    	<strong><?= $this->param('rows_affected') ?></strong> rows affected!.<br />
    	<strong><?= $this->param('time') ?></strong> seconds!.<br />
		<br /><br />

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $this->param("message") ?>
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $lbl ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php elseif ($this->param("process") == "error"): ?>

	<div class="ui negative message">
		<div class="header">
			Error!
		</div>
		<p>
			<strong><i class="warning sign icon"></i></strong> <?= $this->param("message") ?>
		</p>
	</div>

<?php else: ?>

	<div class="ui negative message">
		<div class="header">
			Error!
		</div>
		<p>
			<strong><i class="warning sign icon"></i></strong> Server response not found!
		</p>
	</div>

<?php endif; ?>