<?php if ($this->param("process") == "success"): ?>

	<?php
		$worksheet = $this->param("worksheet");
		$data      = $this->param("data");

		$row_start = $this->param('row_start');
		$row_end   = $this->param('row_end');

		$row_num   = $row_start;

		$uniqid    = $this->param('id');

		$column_errors = $this->param('column_errors');
	?>

    <?php if (count($data)): ?>

		<?php
			$column_names = $data[0];
			$column_names_indexed = [];
		?>

		<?php $i = 1; ?>

		<?php foreach($column_names as $key => $row): ?>
			<?php if (!is_numeric($key)): ?>
				<?php
					$column_names_indexed[$i] = $key;
					$i++;
				?>
			<?php endif; ?>
		<?php endforeach; ?>

		<?php foreach($data as $row): ?>
			<?php $row_num++; ?>
			<tr>
				<?php for ($i = 0; $i < count($data[0]) / 2; $i++): ?>
					<?php if ($i == 0): ?>
						<td><div class="ui ribbon label"><?= $row_num ?></div></td>
					<?php else: ?>
						<?php
							if (is_object($row[$i]) && get_class($row[$i]) == 'DateTime'):
								$row[$i] = $row[$i]->format("Y-m-d H:i:s");
							endif;
						?>
						<?php if (in_array($column_names_indexed[$i+1], $column_errors)): ?>
							<td title="Can't bind value" class="context-menu negative no-binded">
								<span class="ui red label"><i class="warning circle icon"></i>Error</span>
							</td>
						<?php else: ?>
							<td title="<?= htmlentities($row[$i]) ?>" class="context-menu no-binded">
								<?= !is_null($row[$i])
									? '<pre style="margin: 0; max-height: 20px; overflow: hidden;">' .htmlentities($row[$i]) . '</pre>'
									: '<span class="ui orange label">NULL</span>'
								?>
							</td>
						<?php endif; ?>
					<?php endif; ?>
				<?php endfor; ?>
			</tr>
		<?php endforeach; ?>

		<script type="text/javascript">

			/* updates worksheet with last query results */

			var btnContinue = $("#frm-sql-<?= $worksheet ?> button#continue-statement-<?= $worksheet ?>");
			var object = eval(btnContinue.attr("data-object"));

			object.row_start = <?= $this->param('row_start') ?>;
			object.row_end = <?= $this->param('row_end') ?>;
			object.num_rows = <?= $this->param('num_rows') ?>;
			object.time = <?= $this->param('time') ?>;
			object.sql = '<?= $this->param('sql') ?>';

			btnContinue.attr("data-object", "v = " + JSON.stringify(object));

			$("#log-<?= $worksheet ?>").html("<strong><?= $this->param('num_rows') ?></strong> rows!.<br /><strong><?= $this->param('num_fields') ?></strong> fields.<br /><strong><?= $this->param('rows_affected') ?></strong> rows affected!.<br /><strong><?= $this->param('time') ?></strong> seconds!.<br />");

			/* Binds new event for next statement */

			var nextStm = function(event)
			{
		        element = $("#<?= $uniqid ?>")[0];

		        if (element.scrollHeight - element.scrollTop < 240)
		        {
		        	// Make sure for only one execution of next statement
		        	$("#<?= $uniqid ?>")[0].removeEventListener('scroll', nextStm);
		        	$('#continue-statement-<?= $worksheet ?>').trigger('click');
		        }
			}

	    	$("#<?= $uniqid ?>")[0].addEventListener('scroll', nextStm, false);

	    	// contextual menu
	    	$.each($("#<?= $uniqid ?> .context-menu.no-binded"), function(key, cell) {
				cell.addEventListener( "contextmenu", function(e) {

					e.preventDefault();

					/*
					 * Gets the value cell value
					 */

					// when is directly a TD element get the html (this includes PRE element)
					if (e.path[0].nodeName == 'TD')
						var td = $(e.path[0]);
					// when is not a TD element, the user clicks directly inside PRE element, so get outer html
					else
						var td = $(e.path[0]).parent();

					var app_ctx_menu = $("#app-contextual-menu-<?= $uniqid ?>");

					// the title attribute stores the cell value for each cell
					app_ctx_menu.attr('data-text', td.attr('title'));

					var x = e.clientX;
					var y = e.clientY;

					// contextual menu positioning
					app_ctx_menu.show().css('left', x);
					app_ctx_menu.show().css('top', y);
				});

				$(cell).removeClass('no-binded');
	    	});

		</script>

   	<?php endif ?>

<?php endif; ?>