<?php
	$uniqid = $this->param("id");
	$conn   = $this->param("conn");
?>

<form id="frm-sql-<?= $uniqid ?>" action="<?= $this->basePath() . '/public/Connections/Tools/execute' ?>" method="post"
	data-role="ajax-request" data-response="#sql-res-<?= $uniqid ?>">
	<div class="form-group">
		<textarea spellcheck="false" name="sql" id="sql<?= $uniqid ?>" rows="10" ui-codemirror class="form-control" autofocus="autofocus" placeholder="your sql here!"></textarea>
		<input type="hidden" name="conn" value="<?= $conn ?>" />
		<input type="hidden" name="worksheet" value="<?= $uniqid ?>" />
	</div>
    <button class="ui button" type="submit"><span class="glyphicon glyphicon-ok"></span> Execute</button>
    <button style="display: none" class="ui button" type="button" id="execute-statement-<?= $uniqid ?>" data-role="ajax-request" data-response="#sql-res-<?= $uniqid ?>"
    data-url="<?= $this->basePath() . '/public/Connections/Tools/execute' ?>" data-type="post"
    data-object="v = {
    	conn: '<?= $conn ?>', worksheet: '<?= $uniqid ?>',
    	sql: editor<?= $uniqid ?>.getSelection()
    }">Execute selection</button>
    <button style="display: none" class="ui button" type="button" id="continue-statement-<?= $uniqid ?>" data-role="ajax-request"
    data-url="<?= $this->basePath() . '/public/Connections/Tools/execute' ?>" data-type="post"
    data-object="v = {
    	conn: '<?= $conn ?>', worksheet: '<?= $uniqid ?>', sql: '', row_start: '', row_end: '', base64: true
    }"
    data-callback="v = {
		success: function(results)
		{
			$('#sql-res-<?= $uniqid ?> .sql-data table tbody tr:last').after(results);
		}
	}">Next grid</button>
</form><br />

<div id="sql-res-<?= $uniqid ?>">
	<div class="ui blue message">
		<p>
			<strong><i class="info icon"></i></strong> &nbsp;Press <strong>CTRL</strong> + <strong>Enter</strong> to execute selected statement
		</p>
	</div>
</div>

<style>
.CodeMirror-gutter-wrapper {
	left: -29px !important;
}
.CodeMirror-sizer {
	margin-left: 29px !important;
}
.CodeMirror {
    height: 180px;
}
</style>

<script>
	var editor<?= $uniqid ?> = CodeMirror.fromTextArea(document.getElementById("sql<?= $uniqid ?>"), {
	    lineNumbers: true,
	    matchBrackets: true,
	    mode: "text/x-sql",
	    indentUnit: 4,
	    indentWithTabs: true,
	    theme: 'monokai',
	});

	$("#frm-sql-<?= $uniqid ?>")[0].addEventListener('keydown', (event) => {

	  	const keyName = event.key;

		if (keyName === 'Control')
			return;

		if (event.ctrlKey)
		{
			if (keyName === 'Enter')
			{
				// F5 - Execute several statements are not supported yet
				//$("#frm-sql-<?= $uniqid ?> button[type='submit']").trigger('click');
				$("#execute-statement-<?= $uniqid ?>").trigger('click');
			}
	  	}

	}, false);

</script>