<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="icon" href="<?= $this->basePath() ?>/public/img/favicon.png" type="image/x-icon" />
	<link rel="shortcut icon" href="<?= $this->basePath() ?>/public/img/favicon.png" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

	<?php
		$config = include("module/Auth/config/user.config.php");
		$this->setTitle($config["project"]["name"]); $_title = $this->getTitle();
	?>

	<title><?= $this->getTitle() ?></title>

	<link rel="stylesheet" type="text/css" href="<?= $this->basePath(); ?>/public/css/bootstrap.min.css" />

	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/jquery-3.1.0.min.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?= $this->basePath(); ?>/public/js/app.js"></script>

</head>

	<body>

		<nav class="navbar navbar-default">
		  	<div class="container-fluid">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			      	</button>
			      	<a class="navbar-brand" href="<?= $this->basePath() ?>"><?= $config["project"]["name"] ?></a>
			    </div>
		  	</div><!-- /.container-fluid -->
		</nav>

		<div class="container">
			<?= $this->content() ?>

			<!-- update page title -->
			<?php if ($this->getTitle() !== $_title): ?>
				<script type="text/javascript">
					$("head title").text($("head title").text() + ' - <?= $this->getTitle() ?>');
				</script>
			<?php endif; ?>
		</div>

	</body>

</html>