<style>
	@media (min-width: 991.98px) {
		.e404 {
			width: auto !important;
		}

		.show-on-large {
			display: block !important;
		}
	}

	.warning-icon-left {
		float: left;
		font-size: 70px;
		margin-right: 10px;
		line-height: 1.0;
		margin-top: 10px;
	}
</style>

<div class="row">
	<div class="col-sm">
		<h1 class="text-danger" style="margin: 0">Page Not Found!</h1>
		<img src="<?= $this->basePath() ?>/public/img/error-404.png" alt="NOT FOUND" class="e404" style="width: 100%" />
	</div>
	<div class="col-sm">

		<img src="<?= $this->basePath() ?>/public/img/man-exclamation.png" alt="exclamation" class="show-on-large" style="display: none" />

		<div class="alert alert-danger" role="alert">

			<div class="text-danger warning-icon-left">
				<i class="fas fa-exclamation-triangle"></i>
			</div>

			<h3 class="text-danger">404</h3>

			<p class="text-justify">
				The webpage you requested does not exists or had a problem, try to access again later.
				Use the <strong>back</strong>  button to navigate to last page or close this window.
			</p>

		</div>

	</div>
</div>