<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "register-form"): ?>

	<?php
		$types = $this->param('types');
		$fieldTypes = $this->param('fieldTypes');
	?>

	<form class="ui form" id="frm-add-user-connection" data-role="ajax-request" data-response="#add-user-connection-response"
		action="<?= $this->basePath() ?>/public/Workarea/Connections/add" method="post">
		<div class="field">
			<div class="fields">
				<div class="eight wide field">
					<label for="conntype"><?= $intl->translate('Connection type') ?></label>
					<select name="type" id="conntype" onchange="
							var type = $(this).val();
							var fieldTypes = $('#frm-add-user-connection .fields.type');

							$.each(fieldTypes, function(key, htmlEl){

								if ($(htmlEl).attr('data-type') == type)
									$(htmlEl).show();
								else
									$(htmlEl).hide().find('input').val('');
							});
						">
						<option value=""><?= $intl->translate('Selection') ?></option>
						<?php foreach ($types as $type): ?>
							<option value="<?= $type->CONN_TYPE_ID ?>"><?= $type->CONN_TYPE_NAME ?></option>
						<?php endforeach; ?>
					</select>
				</div>
				<div class="eight wide field">
					<label for="aliasname"><?= $intl->translate('Connection name') ?></label>
					<input type="text" id="aliasname" name="aliasname" placeholder="<?= $intl->translate('alias for your connection') ?>" />
				</div>
			</div>
		</div>

		<?php $cols = 3; $k = $cols; $prev_type = null; ?>

		<?php $fieldSize = ""; ?>

		<?php
			switch ($cols):
case 3: $fieldSize = "three"; break;
case 4: $fieldSize = "four"; break;
case 5: $fieldSize = "five"; break;
case 6: $fieldSize = "six"; break;
			endswitch;
		?>

		<?php foreach ($fieldTypes as $type => $fields): ?>

		<?php if (!is_null($prev_type) && $prev_type !== $type): ?>
			<?php $k = $cols; ?>
		<?php endif; ?>

		<?php $prev_type = $type; ?>

		<div class="field">
			<div class="<?= $fieldSize ?> fields type" data-type="<?= $type ?>">
				<?php foreach ($fields as $field): ?>
					<div class="field">
						<label for="field<?= $type . $field->CONN_IDENTI_ID ?>"><?= $field->FIELD_NAME ?></label>
						<input type="text" id="field<?= $type . $field->CONN_IDENTI_ID ?>" name="field[<?= $type ?>][<?= $field->CONN_IDENTI_ID ?>]" placeholder="<?= $field->PLACEHOLDER ?>">
					</div>

					<?php if (++$k % $cols == 0): ?>
			</div>
		</div>
		<div class="field">
			<div class="<?= $fieldSize ?> fields type" data-type="<?= $type ?>">

					<?php endif; ?>

				<?php endforeach; ?>
			</div>
		</div>
		<?php endforeach; ?>

		<button class="ui submit button"><i class="check icon"></i> <?= $intl->translate('Save') ?></button>
		<button class="ui button" type="button" data-role="ajax-request" data-type="post" data-form="#frm-add-user-connection"
			data-url="<?= $this->basePath() ?>/public/Connections/Tools/testConnection" data-response="#add-user-connection-response"
			><i class="play icon"></i> <?= $intl->translate('Test') ?></button>
	</form><br />

	<div id="add-user-connection-response"></div>

	<script type="text/javascript">
		$(function(){
			$("#frm-add-user-connection").find('.fields.type').hide();
		});
	</script>

<?php elseif ($this->param("process") == "process-response"): ?>

	<div class="ui success message">
		<div class="header">
			<?= $intl->translate('Success') ?>!
		</div>
		<p>
			<strong><i class="warning checkmark icon"></i></strong> <?= $intl->translate('Connection added') ?>!
		</p>
	</div>

	<script type="text/javascript">
		$("#frm-add-user-connection")[0].reset();
		$("#btn-list-connections").trigger("click");
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $intl->translate($this->param("message")) ?>!
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>

<script type="text/javascript">
	$('#md-add-connection').modal('refresh');
</script>