<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "success"): ?>

	<?php $id = $this->param("id"); ?>

	<div class="ui success message">
		<div class="header">
			<?= $intl->translate('Success') ?>!
		</div>
		<p>
			<strong><i class="warning checkmark icon"></i></strong> <?= $intl->translate('Connection deleted') ?>!
		</p>
	</div>

	<script type="text/javascript">
		$(function(){
			$("#user-conn-list-item-<?= $id ?>").remove();
		});
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $intl->translate($this->param("message")) ?>!
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>

<script type="text/javascript">
	$('#md-delete-connection').modal('refresh');
</script>