<?php if ($this->param("process") == "success"): ?>

	<?php $connections = $this->param('connections'); ?>

	<?php if (count($connections)): ?>
		<?php foreach ($connections as $connection): ?>
			<div class="item" id="user-conn-list-item-<?= $connection->USER_CONN_ID ?>">
			    <div class="right floated content">
					<div class="ui right dropdown item">
						<i class="dropdown icon"></i>
						<div class="menu">
							<div class="item btn-new-worksheet" data-id="<?= $connection->USER_CONN_ID ?>" data-name="<?= $connection->CONNECTION_NAME ?>">
								<i class="icon terminal"></i> New Worksheet
							</div>
							<div class="item"><i class="icon trash"></i> Delete</div>
						</div>
					</div>
			    </div>
				<i class="large database middle aligned icon"></i>
				<div class="content">
					<a class="header" data-url="<?= $this->basePath() ?>/public/Connections/User/editConnection/id/<?= $connection->USER_CONN_ID ?>"
						data-role="ajax-request" data-type="get" data-response="#activity-response">
						<?= $connection->CONNECTION_NAME ?>
					</a>
					<div class="description">database</div>
				</div>
			</div>
		<?php endforeach; ?>
	<?php else: ?>
		<div class="ui info message">
			<p>
				<strong><i class="warning icon"></i></strong> There aren't connections!
			</p>
		</div>
	<?php endif; ?>

	<script type="text/javascript">
		$('.ui.dropdown').dropdown();
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="ui yellow message">
		<p>
			<strong><i class="warning icon"></i></strong> &nbsp;<?= $this->param("message") ?>
		</p>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $lbl ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php elseif ($this->param("process") == "error"): ?>

	<div class="ui negative message">
		<div class="header">
			Error!
		</div>
		<p>
			<strong><i class="warning sign icon"></i></strong> <?= $this->param("message") ?>
		</p>
	</div>

<?php else: ?>

	<div class="ui negative message">
		<div class="header">
			Error!
		</div>
		<p>
			<strong><i class="warning sign icon"></i></strong> Server response not found!
		</p>
	</div>

<?php endif; ?>