<?php if ($this->param("process") == "success"): ?>

	<div class="ui tabular menu">
		<a class="item active" data-tab="tab-1">
			Workarea
		</a>
		<a class="item" href="<?= $this->basePath() ?>/public/Auth/LogOut/close">
			<i class="power icon"></i> Logout
		</a>
	</div>

	<div class="ui tab active" data-tab="tab-1">
		<div class="ui workarea grid" id='grid-workarea'>
			<div class="three wide column">
				<div class="ui icon buttons">
					<button class="ui button" data-toggle="modal"
							data-url="<?= $this->basePath() ?>/public/Connections/User/addConnection" title="Add connection"
							data-role="ajax-request" data-type="get" data-response="#add-connection-response"
							data-callback="v = {
								before: function() { $('#md-add-connection').modal('show'); },
								success: function() { $('#md-add-connection').modal('refresh'); },
							}">
						<i class="plus icon"></i>
					</button>
					<button class="ui button" data-url="<?= $this->basePath() ?>/public/Connections/User/listConnections"
						data-role="ajax-request" data-type="get" data-response="#list-connections-response" id="btn-list-connections">
						<i class="refresh icon"></i>
					</button>
					<button class="ui button" onclick="

						if ($('#grid-workarea > .one.column').length)
						{
							$('#grid-workarea > .one.column .ui.buttons').removeClass('vertical');

							old_class = $('#grid-workarea > .one.column').attr('class');
							$('#grid-workarea > .one.column').attr('class', old_class.replace('one', 'three'));

							old_class = $('#grid-workarea > .fourteen.column').attr('class');
							$('#grid-workarea > .fourteen.column').attr('class', old_class.replace('fourteen', 'twelve'));

							$(this).html('<i class=\'window minimize icon\'></i>');
						}
						else {
							$('#grid-workarea > .three.column .ui.buttons').addClass('vertical');

							old_class = $('#grid-workarea > .three.column').attr('class');
							$('#grid-workarea > .three.column').attr('class', old_class.replace('three', 'one'));

							old_class = $('#grid-workarea > .twelve.column').attr('class');
							$('#grid-workarea > .twelve.column').attr('class', old_class.replace('twelve', 'fourteen'));

							$(this).html('<i class=\'window restore icon\'></i>');
						}
					">
						<i class="window minimize icon"></i>
					</button>
				</div>
				<div class="ui relaxed divided list" id="list-connections-response">
				</div>
			</div>
			<div class="twelve wide column" id="worksheet-collector">
				<div class="ui pointing secondary menu" style="overflow-x: auto">
					<a class="active item worksheet-item-title" data-tab="home">Home</a>
				</div>
				<div class="ui active tab vertical segment worksheet-item-content" data-tab="home" data-resource="<?= $this->basePath() ?>/public/Connections/Tools/worksheet">
					<div id="activity-response">Welcome to SQL Web Manager!</div>
				</div>
			</div>
		</div>
	</div>

	<div class="ui modal" id="md-add-connection">
		<div class="header">Add connection</div>
		<div class="content">
			<div id="add-connection-response"></div>
		</div>
	</div>

	<div class="ui modal" id="md-delete-connection">
		<div class="header">Delete connection</div>
		<div class="content">
			<div id="delete-connection-response"></div>
		</div>
	</div>

	<script type="text/javascript">
		$(function() {

			$("#btn-list-connections").trigger("click");

			// hide contextual menus
			$("body").delegate("*", "click", function(e) {
				$('.app-contextual-menu').css('display', 'none');
			});

		});
	</script>

<?php elseif ($this->param("process") == "error"): ?>

	<div class="alert alert-danger">
		<strong>Error!</strong> <?= $this->param("message") ?>
	</div>

<?php else: ?>

	<div class="alert alert-danger">
		<strong>Error!</strong> Unknown error
	</div>

<?php endif; ?>