<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "success"): ?>

	<div class="alert alert-success" role="alert">
		<i class="fas fa-check"></i> <?= $intl->translate("Welcome") ?> <em><?= $this->param("username") ?></em>.
	</div>

	<div id="singup-success-message">

		<?php if ($this->param('mail')): ?>
			<p><i class="fas fa-envelope"></i> <?= $intl->translate("We had sent an email to your inbox") ?>.
			<strong><?= $this->param("email") ?></strong>.
			<?= $intl->translate("Please check your email and verify your account") ?>!.</p><br />
		<?php endif; ?>

        <a href="<?= $this->basePath() ?>/public/Auth/LogIn" class="btn btn-primary">
        	<i class="fas fa-sign-in-alt"></i> <?= $intl->translate('Log in') ?>
        </a>
	</div>

	<script type="text/javascript">
		setTimeout(function(){
			$("#frm-singup").hide("slow");
			$("#singup-success-message").show("slow");
		}, 1000);
	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="alert alert-warning" role="alert">
		<i class="fas fa-exclamation"></i> &nbsp;<?= $intl->translate($this->param("message")) ?>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>