<?php $this->setTitle("Registro de usuario"); ?>

<h3>
    <span class="glyphicon glyphicon-user"><small><span class="glyphicon glyphicon-plus-sign"></span></small></span>
    Register form
</h3>

<form id="frm-singup" method="post" data-response="#singup-response" data-role='ajax-request'
    action="<?= $this->basePath() . '/public/Auth/SingUp/attemp' ?>">
    <div class="form-group">
        <label for="username">Username</label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-user"></span></div>
            <input autofocus="autofocus" type="text" id="username" name="username" placeholder="username" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-envelope"></span></div>
            <input autofocus="autofocus" type="email" id="email" name="email" placeholder="email" class="form-control" required="required" maxlength="50" />
        </div>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-lock"></span></div>
            <input type="password" id="password" name="password" placeholder="password" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <label for="password_confirm">Your password again</label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-lock"></span></div>
            <input type="password" id="password_confirm" name="password_confirm" placeholder="password" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-default transparent" type="submit">
            <span class="glyphicon glyphicon-plus"></span> Register now
        </button>
        <a href="<?= $this->basePath() ?>/public/Auth/LogIn"
            class="btn" type="submit"><span class="glyphicon glyphicon-log-in"></span> Log in
        </a>
    </div>
</form>

<div id="singup-response"></div>