<?php if ($this->param("process") == "success"): ?>

	<div class="alert alert-success">
		<strong><span class="glyphicon glyphicon-ok"></span></strong>
		Successfully log in
	</div>

	<div id="login-success-message">
		<p><span class="glyphicon glyphicon-link"></span> Please wait a few seconds while we redirect you...</p>
	</div>

	<script type="text/javascript">

		setTimeout(function(){
			$("#frm-login").hide("slow");
			$("#login-success-message").show("slow");
		}, 1000);

		setTimeout(function(){
			window.location = "";
		}, 2000);

	</script>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="alert alert-warning">
		<strong><span class="glyphicon glyphicon-alert" aria-hidden="true"></span></strong> &nbsp;<?= $this->param("message") ?>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $lbl ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php elseif ($this->param("process") == "error"): ?>

	<div class="alert alert-danger">
		<strong><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span></strong> &nbsp;<?= $this->param("message") ?>
	</div>

<?php else: ?>

	<div class="alert alert-danger">
		<strong><span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span></strong> &nbsp;Unknown error
	</div>

<?php endif; ?>