<?php
    $intl = $this->getController()->translator;
    $this->setTitle($intl->translate("User login"));
?>

<h3> <?= $intl->translate('User login') ?> </h3>

<form id="frm-login" method="post" data-response="#login-response" data-role='ajax-request'
    action="<?= $this->basePath() . '/public/Auth/LogIn/attemp' ?>">
    <div class="form-group">
        <label for="username"><?= $intl->translate('Username') ?></label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-user"></span></div>
            <input autofocus="autofocus" type="text" id="username" name="username" placeholder="<?= $intl->translate('username') ?>" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <label for="password"><?= $intl->translate('Password') ?></label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-lock"></span></div>
            <input type="password" id="password" name="password" placeholder="<?= $intl->translate('password') ?>" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-default transparent" type="submit">
            <span class="glyphicon glyphicon-log-in"></span> <?= $intl->translate('Log in') ?>
        </button>
        <a href="<?= $this->basePath() ?>/public/Auth/SingUp"
            class="btn" type="submit"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?= $intl->translate('Register') ?>
        </a>
    </div>
</form>

<div id="login-response"></div>