<?php $this->setTitle("Inicio de sesión"); ?>

<h3>
    <span class="glyphicon glyphicon-user"><small><span class="glyphicon glyphicon-log-in"></span></small></span>
    Log In
</h3>

<form id="frm-login" method="post" data-response="#login-response" data-role='ajax-request'
    action="<?= $this->basePath() . '/public/Auth/LogIn/attemp' ?>">
    <div class="form-group">
        <label for="username">Username</label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-user"></span></div>
            <input autofocus="autofocus" type="text" id="username" name="username" placeholder="username" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <div class="input-group">
            <div class="input-group-addon transparent"><span class="glyphicon glyphicon-lock"></span></div>
            <input type="password" id="password" name="password" placeholder="password" class="form-control" required="required" maxlength="20" />
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-default transparent" type="submit">
            <span class="glyphicon glyphicon-log-in"></span> Log in
        </button>
        <a href="<?= $this->basePath() ?>/public/Auth/SingUp"
            class="btn" type="submit"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Register
        </a>
    </div>
</form>

<div id="login-response"></div>